### ISSUE TITLE
Setup demo database  TypeError: Atk4\Ui\JsCallback::_getProperAction(): Return value must be of type Atk4\Ui\Js\JsExpressionable, array returned 

### ISSUE THREAD

**Issue by gnuhub** [atk4/login#106]
TypeError: Atk4\Ui\JsCallback::_getProperAction(): Return value must be of type Atk4\Ui\Js\JsExpressionable, array returned

**Comment by mvorisek** [comment]
Hi, is this bug still present? If yes, please provide a simple repro steps.

**Comment by mvorisek** [comment]
@mkrecek234 maybe you want to fix this?
