### ISSUE TITLE
Compatible with atk4/ui 5?

### ISSUE THREAD

**Issue by highmountainmedia** [atk4/login#108]
I can't for the life of me get atk4/login 3.1.0 installed with atk4/ui 5.0.0. It shows last commits were to update to latest atk4/ui version, but 3.1.0 refuses to allow ui/5. Am I missing something?

https://packagist.org/packages/atk4/login shows this as still requiring atk4/ui 3.1.0. Is this not up to date?

**Comment by brianmoney** [comment]
Same issue. Can any dev advise?
