### ISSUE TITLE
minimum stability in dev-develop branches should always require dev-develop branch of other atk repositories

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [atk4/login#16]
https://github.com/atk4/login/blob/63d0fb8023b411075386962d5351811aa65e9658/composer.json#L18

dev-develop branch should always point to other dev-develop branch or it get conflicts while developing on nightly build system

example: 
Let's assume I am creating an application and since right-now a lot in development is going on in ui/data develop branches and these branches are my best option to include in my composer requirements.

Now, with dev-develop requirement of ui /schema and login, composer gets conflicts in minimum stability requirements. 

So my requirements as follows 

```
"minimum-stability": "dev",
"require": {
        "myapp/namespace":"dev-master",
        "atk4/ui": "dev-develop",
        "atk4/login": "dev-develop"
    },
    "require-dev": {
        "atk4/schema": "^1.1.1",   <= or even dev-develop both giving errors
        "phpunit/phpunit": "<6",
        "phpunit/phpcov": "^3.0",
        "codeclimate/php-test-reporter": "*",
        "behat/behat": "^3.4",
        "behat/mink-extension": "^2.2",
        "fzaninotto/faker": "*"
    }

```
never gets installed/updated with composer

**Comment by gowrav-vishwakarma** [comment]
For now, updating composer and treating dev-develop as recent branch solves the problem 

```
"require": {
        "my/repo":"dev-master",
        "atk4/ui": "dev-develop as 1.6.1",
        "atk4/login": "dev-develop"
    },
```

**Comment by DarkSide666** [comment]
see @romaninsh comment here https://github.com/atk4/ui/issues/641#issuecomment-456386581
