### ISSUE TITLE
Demo from this addon do not work

### ISSUE THREAD

**Issue by eletec** [atk4/login#21]
Hi !

I try this addon using standard installation with 1.7.1 release atk/ui
using composer require atk/login
demos fail -> file ConfigTrait.php used in demos is not present in atk/core 1.7.1....

I also test this addon in standalone mode
composer could not resolve during update
 "atk4/data": "dev-feature/action-fields as dev-develop"

action-fields not found in packages

I replace by dev-develop to resolve dependencies but finally ig get this error 
admin-roles.php
atk4\core\Exception Unable to set property for the object
object:atk4\ui\CRUD ()
property:"formDefault"
value:{"0":"Form","layout":"Columns"}
9 | 64\www\login\vendor\atk4\ui\src\View.php: 274 | atk4\core\Exception | __construct

How to get a correct environnement using this addon ?

Thanks

**Comment by abbadon1334** [comment]
Hi,
yes is broken due to the finalization of release 2.0.

if you want to check the functionalities you can try use this dep : 
```
        "atk4/ui": "dev-develop#dae88ae0bd5b9febb7a03067ecbeb5f39c4f5099",
        "atk4/data": "dev-develop#0f34d74ff7091b224e72a666f034be40cb9972bb as 1.1",
        "atk4/login": "dev-develop@dev",
```
If you still get the error join the gitter channel : https://gitter.im/atk4/atk4

**Comment by romaninsh** [comment]
@abbadon1334 release 2.0 is now complete - can we re-visit this and get it finished?

**Comment by abbadon1334** [comment]
this is solved, but needs some work on ACL. i need @DarkSide666 to look into it

**Comment by eletec** [comment]
@abbadon1334 How can I try ?

**Comment by eletec** [comment]
@abbadon1334 Whats new in release 2 ? I could not find a listing whith all functionnalities

**Comment by DarkSide666** [comment]
I will shortly recheck and extend this repo. Please stay tuned :)

**Comment by acicovic** [comment]
Hi,

This is almost a year old and many new releases have been released since then. Can anybody confirm if this is still an issue or not?

Else, I just propose to close this and we can reopen it if needed.
