### ISSUE TITLE
app->stickyGet is lost after authentication?

### ISSUE THREAD

**Issue by mkrecek234** [atk4/login#41]
I have an $app->stickyGet parameter and also authenticate using atk4/login. However, if the autentication is done and user logged in, the stickyGet is missing.

**Comment by acicovic** [comment]
@mkrecek234 did the mentioned PR solve the issue?

**Comment by mkrecek234** [comment]
No, this still is an issue in atk4 2.2 and corresponding login repo...

**Comment by DarkSide666** [comment]
Which atk4/login release (or develop) are you using?

**Comment by mkrecek234** [comment]
Was an issue in develop branch since creation of this issue; Still is one in 2.2 confirmed. 2.3 and develop not tested but I assume this is not a bug but a missing feature.

**Comment by DarkSide666** [comment]
There was big changes in how stickyGet is treated in UI repo not long ago. Probably that's what cause this issue.
