### ISSUE TITLE
addHook/onHook issue - Most recent develop version breaks ACL code

### ISSUE THREAD

**Issue by mkrecek234** [atk4/login#43]
After update today, this error occurs - I changed the addHook to onHook. Are there other refactoring implications that I missed?

Critical Error
TypeError : Argument 2 passed to atk4\data\Persistence::onHook() must be an instance of Closure or null, array given, called in /ATK4/crm/vendor/atk4/login/src/Auth.php on line 201

**Comment by DarkSide666** [comment]
Yes this will no more be compatible with current develop branches.
We will have to fix it, but in short:
- addHook to onHook
- 1st parameter should be class HOOK_* constant not string anymore
- 2nd parameter should be closure only, no more callables. If you really want callable, then use it like:
`\Closure::fromCallable([$object, 'method_name'])`

**Comment by mkrecek234** [comment]
Resolved with the mentioned PRs
