### ISSUE TITLE
Login not working with atk4 2.2

### ISSUE THREAD

**Issue by bedengler** [atk4/login#53]
Calling atk4 login in atk4 2.2 via 
`$app->auth = $app->add([new \atk4\login\Auth()]);`

results in "atk4\core\Exception: Seed class is not a subtype of static class "

Calling it via 
`$app->auth = $app->add(new \atk4\login\Auth()); // (without brackets - like we did it in previous version)`

results in "atk4\core\Exception: Object is not an instance of static class "

Solutions?

**Comment by bedengler** [comment]
```
include __DIR__."/../vendor/autoload.php";
$db = new \atk4\data\Persistence\SQL('mysql:dbname=dbname;host=localhost', 'root', 'root');

$app = new \atk4\ui\App();
$app->db = $db;
$app->initLayout([\atk4\ui\Layout\Admin::class]);

// ADD THIS CODE:
$app->add([\atk4\login\Auth::class])
    ->setModel(new User($app->db));
```

results in the following message: 
![Bildschirmfoto 2020-08-08 um 17 47 25](https://user-images.githubusercontent.com/17435772/89803272-df55a080-db32-11ea-9e07-9354021108a1.jpg)

**Comment by FabulousGee** [comment]
Not sure what's the issue on your side honestly, but I added the changes from the Pull Request to add compatibility for v2.2 ( https://github.com/atk4/login/pull/56 ) and then I can use it like this:
```
$this->auth = $this->add(new \app\system\Auth());
$this->auth->setModel(new \app\models\UserModel($this->db), 'email');
```
"$this" in my context is "$app" in yours.

The underlying stuff is from atk4 extended since I wanted some localisation etc.

**Comment by acicovic** [comment]
@bedengler have you managed to solve your issue?

**Comment by DarkSide666** [comment]
@bedengler which atk4/login release (or develop branch) are you using with atk 2.2 ?

**Comment by webbird** [comment]
I am having the same issue.

atk4/ui Version 2.3.5
atk4/data Version 2.3.6
atk4/login - cannot find any version info there, I used **"atk4/login": "*"** in my composer.json

**Comment by PhilippGrashoff** [comment]
Hi there,

auth does not need to be added to App using App::add(). This method is only to add Views to the render tree. The error message reflects this.

All you need to do is `$app->auth = new \Atk4\Login\Auth();`

Best regards
Phliipp

**Comment by webbird** [comment]
Ah! Thank you! I followed the installation instructions:

    // ADD THIS CODE:
    $app->add(new \Atk4\Login\Auth())
        ->setModel(new User($app->db));

After changing this it works.

**Comment by webbird** [comment]
Aftereffect:

"Critical Error
Error: Call to undefined method atk4\data\Reference\HasOne::withTitle()"

A method named **withTitle()** is only avialable in **HasOneSql**.

atk4\login\Model\User line 37:

`$this->hasOne('role_id', [Role::class, 'our_field' => 'role_id', 'their_field' => 'id', 'caption' => 'Role'])->withTitle();`

Fixed this for now by removing `->withTitle()`.

**Comment by PhilippGrashoff** [comment]
> Ah! Thank you! I followed the installation instructions:
> 
> ```
> // ADD THIS CODE:
> $app->add(new \Atk4\Login\Auth())
>     ->setModel(new User($app->db));
> ```
> 
> After changing this it works.

Hello, would you like to create a PR to change the outdated documentation?

**Comment by webbird** [comment]
Jep.

**Comment by DarkSide666** [comment]
Outdated readme PR fixed and merged.

@webbird About _Error: Call to undefined method atk4\data\Reference\HasOne::withTitle()"_ don't you use SQL based persistence? I guess atk4/login is supposed to work correctly only with SQL based persistences.

**Comment by webbird** [comment]
I just used atk4\login\Model\User which calls HasOne(). Full code:

    $app->db = new \atk4\data\Persistence($dsn);

    $app->templateClass = \atk4\ui\Template::class;
    $app->initLayout([\atk4\ui\Layout\Admin::class]);

    $app->auth = new \atk4\login\Auth();
    $app->auth->model = new \atk4\login\Model\User($app->db);

The only thing I did in addition is to set $dsn.

Using Atk4 namespace (uppercase A) does not work for me as the namespace is

`namespace atk4\login\Model;`

(In atk4\login\Model\User latest build; changed to Atk4 in dev)

**Comment by DarkSide666** [comment]
Ah I see, probably I should release it to have proper namespace in release not just dev.

About dsn - do you use mysql or sqlite or what?

**Comment by webbird** [comment]
MariaDB to be really precise. :D

**Comment by DarkSide666** [comment]
Hmm... Then it should automatically use HasOneSql class not HasOne...
