### ISSUE TITLE
Composer repo seems different from Github

### ISSUE THREAD

**Issue by bedengler** [atk4/login#55]
Is it possible that Composer doesn‘t have the most actual version of atk4/login? 
I have cleared the cache several times, deleted the repository manually etc.
I‘m using the dev-developer version of all repositories of atk4 (+add-ons).
I have seen all the recent changes when I inspected the closed PRs on Github.
But they seem to be missing when I download atk4/login through Composer.

That‘s really strange!

How do you manage your packages? 
Is your Composer repo always the same as on Github?
Is the Git Hook to Packagist active?

Btw: I‘m on Mac OS 10.13.6

**Comment by DarkSide666** [comment]
Which atk4/login branch are you using?

Sometimes composer cache plays bad tricks :)

**Comment by bedengler** [comment]
I realized it was due to a wrong composer.json. With all the adjustments etc. I ended up with a "*" instead of "dev-develop" in the version. 
Everything fine now...
