### ISSUE TITLE
Preference form not working

### ISSUE THREAD

**Issue by mkrecek234** [atk4/login#64]
A fresh install on 2.2 or develop branch has the following issue - the user preference pane is not working. Javascript has the error "Can't find variable: $".

![image](https://user-images.githubusercontent.com/28671486/96734873-44433780-13bb-11eb-8138-ec33c8f30afb.png)

**Comment by mkrecek234** [comment]
I could check that the virtual page link is missing this parameter:
&__atk_callback=1

**Comment by DarkSide666** [comment]
Which atk4/login release (or develop branch) are you using?

**Comment by mkrecek234** [comment]
see above - issue seen with 2.2 and develop brach. Checked out fresh install and tested demo

**Comment by DarkSide666** [comment]
> see above - issue seen with 2.2 and develop brach. Checked out fresh install and tested demo

Ouch, sorry. I somehow missed that in issue description :)
