### ISSUE TITLE
Support for multiple user levels

### ISSUE THREAD

**Issue by vegax87** [atk4/login#7]
Now we have a basic "is_admin" boolean condition but I think it's better to extend it in order to support multiple user levels with a vertical hierarchy (Admin, Moderator, Normal user) or separate groups (Admin, Customer, Supplier)

**Comment by acicovic** [comment]
Hi,

My understanding is that the is_admin flag is just a demonstration. For most use cases we should create our own users model. What you describe can be implemented using a users model and conditions for anyone that needs it. You could also have another table with user levels or groups.

This request is old and I don't think it will be implemented by the core team nor that it is absolutely needed in the add-on. So this issue should probably be closed.

@romaninsh I can't close issues so I let you do this if you agree.

**Comment by DarkSide666** [comment]
This is now implemented in https://github.com/atk4/login/commit/242906d6c24261d940b925ec550b08fc289206f6.
User roles, permissions on model fields, actions, conditions, ACL controller.
