### ISSUE TITLE
Sticky parameters lost after login

### ISSUE THREAD

**Issue by mkrecek234** [atk4/login#79]
Steps to reproduce:
- User opens a specific link unauthorized, e.g. customer.php?id=1234 
- Since unauthorized, login form is shown, and user authenticates
- stickyGet parameters are lost then, resulting in a URL called customer.php

Desired behaviour:
- stickyGet parameters survive authentication

Checked to be still an issue in most recent develop and 3.0 releases

**Comment by mvorisek** [comment]
I think this is about remembering the full URL before redirect

**Comment by mvorisek** [comment]
mkrecek
- Atk4/Login: Situation today: You open eg. a link in the demo directly to /admin-users.php?parameter=whatever - as you are not authorized, automatically the login screen opens, and you authenticate.
- It then forwards you to /admin-users.php omitting the URL parameters.
- The same happens also if you go to "Preferences" upright in the user menu: say you are on page admin-users.php?parameter=whatever. If you then go to Preferences, you save, then it is forwarded to admin-users.php without parameters. 

Desired behaviour: - All sticky parameters/ all parameters are kept also after authentication or after editing Preferences menu.   


mvorisek
so you want to return to the original URL incl. query string, right?

mkrecek
Yes - use case: a user is logged on the system and has opened any page (including any parameters) - he passes the link to another non-logged-in user - when he opens it, he should see the login screen (works in atk4/login), login and then views the correct page.

**Comment by mvorisek** [comment]
Steps to reproduce:

0. assume no user is logged in (or log out)
1. open `demos/acl-clients.php?parameter=whatever`
2. log in
3. notice the URL is not the one from step 1.
