### ISSUE TITLE
Privilege Escalation in User Preferences

### ISSUE THREAD

**Issue by vegax87** [atk4/login#9]
This poses a serious security risk because if the Preferences form inherits all fields of the User model without any way to hide them... every normal user can become an admin
 
https://github.com/atk4/login/blob/71d402fddf876075055e7905f4012671767b4cca/src/Auth.php#L143

**Comment by DarkSide666** [comment]
Currently preferences form just use all available fields from user model https://github.com/atk4/login/blob/develop/src/Auth.php#L188.

We could add something like
```
// only admin can should be able to change this field value
if ($f = $this->user->hasElement('is_admin')) {
    $f->read_only = $f->read_only || !$f->get();
}
```

**Comment by acicovic** [comment]
If this is resolved let's close it because for a visitor it's like we have a privilege escalation problem since July 2018!

**Comment by DarkSide666** [comment]
No problem at all :) Solved.

**Comment by cx-joao-delgado** [comment]
Hello, since the PR was rejected can you please tell me if the issue is already solved and how?


Thanks in advance
